=== stoflom/TreesBackend/MongoDB/schema-SATrees-genuscols-standardJSON.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "_id",
    "authority",
    "family",
    "hyperlinks",
    "name"
  ],
  "properties": {
    "_id": {
      "$ref": "#/$defs/ObjectId"
    },
    "authority": {
      "type": "string"
    },
    "cnames": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "language",
          "names"
        ],
        "properties": {
          "language": {
            "type": "string"
          },
          "names": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "comments": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "reference",
          "text"
        ],
        "properties": {
          "reference": {
            "type": "string"
          },
          "text": {
            "type": "string"
          }
        }
      }
    },
    "family": {
      "type": "string"
    },
    "hyperlinks": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "language",
          "link",
          "org"
        ],
        "properties": {
          "language": {
            "type": "string"
          },
          "link": {
            "type": "string"
          },
          "org": {
            "type": "string"
          }
        }
      }
    },
    "name": {
      "type": "string"
    }
  },
  "$defs": {
    "ObjectId": {
      "type": "object",
      "properties": {
        "$oid": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{24}$"
        }
      },
      "required": [
        "$oid"
      ],
      "additionalProperties": false
    }
  }
}

=== stoflom/TreesBackend/MongoDB/genuscols-sample.json
{
  "_id": {
    "$oid": "622a132d4953a86709cb95ab"
  },
  "name": "Abutilon",
  "authority": "Mill.",
  "family": "Malvaceae",
  "comments": [
    {
      "text": "(in narrow sense)",
      "reference": "dnsat"
    }
  ],
  "cnames": [
    {
      "names": [
        "Chinese lanternbosse"
      ],
      "language": "Afr"
    },
    {
      "names": [
        "Chinese-lanterns"
      ],
      "language": "Eng"
    }
  ],
  "hyperlinks": [
    {
      "language": "Afr",
      "link": "https://af.wikipedia.org/wiki/Abutilon",
      "org": "Wikipedia"
    },
    {
      "org": "Wikipedia",
      "link": "https://en.wikipedia.org/wiki/Abutilon",
      "language": "Eng"
    }
  ]
}
