=== stoflom/TreesBackend/MongoDB/schema-SATrees-familycols-standardJSON.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": [
    "_id",
    "cnames",
    "genuslist",
    "hyperlinks",
    "name"
  ],
  "properties": {
    "_id": {
      "$ref": "#/$defs/ObjectId"
    },
    "cnames": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "language",
          "names"
        ],
        "properties": {
          "language": {
            "type": "string"
          },
          "names": {
            "type": "array",
            "items": {
              "type": [
                "string",
                "null"
              ]
            }
          }
        }
      }
    },
    "comments": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "reference",
          "text"
        ],
        "properties": {
          "reference": {
            "type": "string"
          },
          "text": {
            "type": "string"
          }
        }
      }
    },
    "genuslist": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "hyperlinks": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "language",
          "link",
          "org"
        ],
        "properties": {
          "language": {
            "type": "string"
          },
          "link": {
            "type": "string"
          },
          "org": {
            "type": "string"
          }
        }
      }
    },
    "name": {
      "type": "string"
    }
  },
  "$defs": {
    "ObjectId": {
      "type": "object",
      "properties": {
        "$oid": {
          "type": "string",
          "pattern": "^[0-9a-fA-F]{24}$"
        }
      },
      "required": [
        "$oid"
      ],
      "additionalProperties": false
    }
  }
}

=== stoflom/TreesBackend/MongoDB/familycols-sample.json
{
  "_id": {
    "$oid": "626be5e35a22d388e0914528"
  },
  "genuslist": [
    "Anisotes",
    "Brillantaisia",
    "Duvernoia",
    "Justicia",
    "Mackaya",
    "Metarungia",
    "Sclerochiton"
  ],
  "cnames": [
    {
      "language": "Eng",
      "names": [
        "lipflower family"
      ]
    },
    {
      "language": "Afr",
      "names": [
        "lippeblomfamilie"
      ]
    }
  ],
  "name": "Acanthaceae",
  "hyperlinks": [
    {
      "org": "Wikipedia",
      "link": "https://af.wikipedia.org/wiki/Acanthaceae",
      "language": "Afr"
    },
    {
      "link": "https://en.wikipedia.org/wiki/Acanthaceae",
      "language": "Eng",
      "org": "Wikipedia"
    }
  ]
}
